name: Build & Push Docker Image to ACR

on:
  push:
    branches: [ main ]

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}    # e.g. vanfmly.azurecr.io
  IMAGE_NAME:       ${{ vars.IMAGE_NAME }}          # e.g. cfddns

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      # your SP JSON

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.AZURE_CLIENT_ID }}         # exported by azure/login
          password: ${{ env.AZURE_CLIENT_SECRET }}     # exported by azure/login

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: ./_src
          file:    ./_src/CloudflareDdns.Server/Dockerfile
          push:    true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
