name: Build & Push Docker Image to ACR

on:
  push:
    branches: [ main ]

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}    # vanfmly.azurecr.io
  IMAGE_NAME:       ${{ vars.IMAGE_NAME }}          # cfddns

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login via Azure CLI
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}.split('.')[0]

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: ./_src
          file:    ./_src/CloudflareDdns.Server/Dockerfile
          push:    true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
