name: Build & Push Docker Image to ACR

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  IMAGE_NAME:     ${{ vars.IMAGE_NAME }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate to Azure with your SP (sets AZURE_CLIENT_ID & AZURE_CLIENT_SECRET)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Docker login using SP credentials directly
      - name: Docker login to ACR
        run: |
          docker login ${{ env.ACR_LOGIN_SERVER }} \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET
        # SP app/client ID  → username
        # SP password/secret → password :contentReference[oaicite:0]{index=0}

      # 4. Build & Push
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./_src
          file:    ./_src/CloudflareDdns.Server/Dockerfile
          push:    true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
