name: Build & Push Docker Image to ACR

on:
  push:
    branches:
      - main

env:
  # Make sure this is the *full* registry DNS name:
  # e.g. myacr.azurecr.io (not just "myacr")
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  IMAGE_NAME:       ${{ vars.IMAGE_NAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        # non-interactive login, piping the SP secret on stdin
        run: |
          echo "$AZURE_CLIENT_SECRET" | docker login "$ACR_LOGIN_SERVER" \
            --username "$AZURE_CLIENT_ID" \
            --password-stdin

      - name: Build & Push to ACR
        uses: docker/build-push-action@v5
        with:
          context: ./_src
          file:    ./_src/CloudflareDdns.Server/Dockerfile
          push:    true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
