name: Build & Push Docker Image to ACR

on:
  push:
    branches:
      - main   # or whatever branch you prefer

env:
  # Your ACR login server, e.g. devvcloudflaredns.azurecr.io
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  # Image name (you can change this)
  IMAGE_NAME: devv-cloudflaredns

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Azure
      #    You must have created a Service Principal with pull & push rights
      #    and stored its JSON “sdk-auth” output in the AZURE_CREDENTIALS secret.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Build and push the image
      - name: Build and push to ACR
        uses: docker/build-push-action@v5
        with:
          context: ./_src/CloudflareDdns.Server
          file:    ./_src/CloudflareDdns.Server/Dockerfile
          push:    true
          tags:    |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

